const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import fs from 'node:fs';
import http from 'node:http';
import assert from 'node:assert/strict';
import path from 'node:path';
const artifactDir=process.env.BROWSER_ARTIFACT_DIR || 'test-artifacts';
fs.mkdirSync(artifactDir,{recursive:true});
const server=http.createServer((req,res)=>{ const js=req.url==='/rocket-launch-card.js';res.setHeader('Content-Type',js?'text/javascript':'text/html');res.end(fs.readFileSync(new URL(js?'../rocket-launch-card.js':'./fixtures/countdown.html',import.meta.url))); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {}),headless:true});
const page=await browser.newPage({viewport:{width:860,height:930}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
let checks=0;const check=(value,label)=>{assert.ok(value,label);checks++;console.log('PASS '+label)};
try {
await page.goto(`http://127.0.0.1:${server.address().port}`);
const root=page.locator('#countdown .rl-root');
check(await page.locator('#countdown .rl-stars').count()===0,'no stray starfield or moon in countdown');
check(await page.locator('#countdown .cd-wrap').evaluate(e=>getComputedStyle(e).borderLeftWidth)==='1px','inset stripe removed');
check(await page.locator('#countdown .cd-big').evaluate(e=>getComputedStyle(e).color)==='rgb(180, 154, 255)','violet timer');
await page.locator('#countdown').screenshot({path:path.join(artifactDir,'countdown-preview-desktop.png')});
await root.click();
check(await page.locator('dialog').evaluate(e=>e.open),'tap opens native modal');
check(await page.locator('dialog rocket-launch-card .rl-row').count()===2,'popup contains full three-launch list');
await page.locator('dialog .rl-row').first().click();
check(await page.locator('dialog .rl-row').first().getAttribute('aria-expanded')==='true','popup accordion works');
await page.evaluate(()=>{fixtureHass.states[baseConfig.entity].attributes.launches[0].mission_name='Updated live mission';card.hass=fixtureHass;});
check(await page.locator('dialog .hero-name').textContent()==='Updated live mission','open popup receives hass updates');
await page.screenshot({path:path.join(artifactDir,'countdown-popup-desktop.png'),fullPage:true});
await page.keyboard.press('Escape');
check(await page.locator('dialog').count()===0,'Escape dismisses and removes popup');
check(await root.evaluate(e=>e.getRootNode().activeElement===e),'focus returns to stable countdown root');
await page.evaluate(()=>{fixtureHass.states[baseConfig.entity].attributes.launches[0].net=new Date(Date.now()+3600000).toISOString();card.hass=fixtureHass;});
const tickBefore=await page.locator('#countdown .cd-big').textContent();
await page.waitForTimeout(1200);
check(await page.locator('#countdown .cd-big').textContent()!==tickBefore,'countdown actually repaints during focus test');
check(await root.evaluate(e=>e.getRootNode().activeElement===e),'focus survives countdown tick');
await page.keyboard.press('Shift+Enter');
check(await page.evaluate(()=>calls.filter(c=>c.type==='hass-more-info').length)===1,'Shift+Enter runs hold action');
await root.hover();await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up();
check(await page.evaluate(()=>calls.filter(c=>c.type==='hass-more-info').length)===2,'pointer hold fires exactly once');
check(await page.locator('dialog').count()===0,'hold does not also tap/open popup');
// Movement cancels both hold and tap.
const box=await root.boundingBox();await page.mouse.move(box.x+30,box.y+50);await page.mouse.down();await page.mouse.move(box.x+70,box.y+90);await page.mouse.up();
check(await page.locator('dialog').count()===0,'drag does not open popup');
await page.evaluate(()=>card.setConfig({...baseConfig,tap_action:{action:'navigate',navigation_path:'#launches'}}));
await root.click();check(await page.evaluate(()=>location.hash)==='#launches','tap navigates to hash popup/dashboard path');
check(await page.evaluate(()=>calls.some(c=>c.type==='location-changed')),'navigation notifies Home Assistant router');
await page.evaluate(()=>card.setConfig({...baseConfig,tap_action:{action:'fire-dom-event',browser_mod:{service:'browser_mod.popup'}}}));await root.click();
check(await page.evaluate(()=>calls.some(c=>c.type==='ll-custom'&&c.browser_mod.service==='browser_mod.popup')),'external popup event bubbles intact');
await page.evaluate(()=>card.setConfig(baseConfig));await root.click();await page.locator('dialog button').click();check(await page.locator('dialog').count()===0,'close button dismisses');
await root.click();await page.mouse.click(5,5);check(await page.locator('dialog').count()===0,'backdrop dismisses');
await page.evaluate(()=>{card.setConfig({...baseConfig,accent_color:'#f0a060'});});
check(await page.locator('#countdown .cd-big').evaluate(e=>getComputedStyle(e).color)==='rgb(240, 160, 96)','custom accent applies without reload');
await page.evaluate(()=>{editor.style.display='block';});
const editorTap=page.locator('#editor select[data-action="tap_action"]');
await page.evaluate(()=>{editor.addEventListener('config-changed',e=>window.editorConfig=e.detail.config)});
await editorTap.selectOption('navigate');await page.locator('#editor [data-action-path="tap_action"]').fill('/lovelace/launches');await page.locator('#editor [data-action-path="tap_action"]').press('Tab');
check(await page.evaluate(()=>editorConfig.tap_action.navigation_path)==='/lovelace/launches','visual editor saves navigation action/path');
await page.evaluate(()=>{editor.style.display='none';card.setConfig(baseConfig);});
await page.evaluate(()=>{fixtureHass.states[baseConfig.entity].attributes.launches[0].mission_name='Starlink Group 15-24';card.hass=fixtureHass;});
await page.setViewportSize({width:390,height:844});
check(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'mobile page has no horizontal overflow');
await page.locator('#countdown').screenshot({path:path.join(artifactDir,'countdown-preview-mobile.png')});
await root.click();check(await page.locator('dialog').evaluate(e=>e.getBoundingClientRect().width<=390),'popup fits phone width');
await page.screenshot({path:path.join(artifactDir,'countdown-popup-mobile.png'),fullPage:true});
await page.keyboard.press('Escape');
await page.evaluate(()=>{card.setConfig({...baseConfig,trigger_hours:1});fixtureHass.states[baseConfig.entity].attributes.launches[0].net=new Date(Date.now()+8*3600000).toISOString();card.hass=fixtureHass;});
check(await page.locator('#countdown .rl-dormant').count()===1,'dormant front card still available');
await root.click();check(await page.locator('dialog').count()===1,'dormant card opens full launch popup');
await page.evaluate(()=>card.remove());check(await page.locator('dialog').count()===0,'removing card cleans up open dialog');
const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const touch=await touchContext.newPage();touch.on('pageerror',e=>errors.push(String(e)));
await touch.goto(`http://127.0.0.1:${server.address().port}`);
const touchBox=await touch.locator('#countdown .rl-root').boundingBox();
const client=await touch.context().newCDPSession(touch);
await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBox.x+40,y:touchBox.y+50}]});
await touch.waitForTimeout(650);
await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
check(await touch.evaluate(()=>calls.filter(c=>c.type==='hass-more-info').length)===1,'mobile touch hold runs once');
check(await touch.locator('dialog').count()===0,'mobile touch hold suppresses popup tap');
await touch.touchscreen.tap(touchBox.x+40,touchBox.y+50);
check(await touch.locator('dialog').count()===1,'mobile touch tap opens popup');
await touch.evaluate(()=>{fixtureHass.states[baseConfig.entity].attributes.launches.forEach(l=>{l.status_abbrev='Success';l.status='Launch Successful';});card.hass=fixtureHass;});
check(await touch.locator('#countdown').evaluate(e=>e.style.display)==='none','live success update hides completed countdown');
check(await touch.locator('dialog').count()===0,'completion closes existing popup');
check(await touch.locator('#countdown').evaluate(e=>e._tickTimer===null),'completion stops countdown timer');
await touchContext.close();
check(errors.length===0,'no browser runtime errors: '+errors.join(';'));
console.log(`${checks} browser checks passed`);
} finally {await browser.close();await new Promise(r=>server.close(r));}

